version: '3.8'

services:
  vitaplsek-e2e-db:
    image: postgres:13.8
    container_name: vitaplsek-e2e-db
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - vitaplsek-e2e-db-data:/var/lib/postgresql/data

volumes:
  vitaplsek-e2e-db-data:
